### PR TITLE
[WIP] enable dispatch to multiple backends

### PR DESCRIPTION
**Pull request by alisterburt**
started working through adding the possibility of dispatch to multiple backends - still needs work but so far
- `FrontEndFor` now has a list of multiple `_backends` accessible through `FrontEndFor.backend_adaptors()`
- `FrontEndFor.native` has become `FrontEndFor.native_objects` which is currently a dict of adaptor type -> adaptor, this needs fixing as it's not easy for subclasses to access their native object yet

### CODE REVIEW

**Comment by tlambert03** [comment]
yay!  it sparks a lot of joy to see you playing with this :)

let me know if you want to have a zoom chat at any point (haven't looked to closely at the code yet).

copying some of the rationale for this from our chat elsewhere:

> an example of where the one backend adaptor per object thing potentially being limiting is the inability to switch out points for quads to overcome point size limitations on mac, you already noted the limitation, do you have thoughts on how to solve it/make configuration easy?

>> In that case, do you need to swap it out, and still have one adaptor at any given time? Or would you actually want to have two backend objects representing/following the same model object simultaneously?

>I guess you could implement it either way, you could either have one slightly more complex adaptor which can dispatch to either backend object or multiple adaptors for the different case and put the dispatch upstream somewhere... not immediately sure what's better

------ 

>>The reason I noted the limitation is when I was writing up docs in the abstract, and I said "It should be possible for a given model object to have multiple views... possible even multiple backends". Then I realized that wasn't currently possible. But the solution should be kinda trivial... amounting to [FrontEnd._backend](https://github.com/tlambert03/microvis/blob/4b82957561ec6193bc05b9844084602fdf3b969e/src/microvis/core/_base.py#L76) being a pointer not to a single object, but a list of backend objects:
>> ```py
>> _backend: Union[T, None] = PrivateAttr(None)
>> # changes to
>> _backend: List[T] = PrivateAttr([])
>> ```
>> ...with some way to make sure that each backend gets the backend-appropriate object.

**Comment by tlambert03** [comment]
also, apologies for the merge conflicts. I have one more likely coming (adding tests for view, and splitting the module slightly)

**Comment by alisterburt** [comment]
I've been coming down similarly, I think multiple (potentially simultaneous) backends is a good thing to make sure we have now but multiple adaptors per backend shouldn't be necessary because, as you said, implementing dispatch to an alternative adaptor implementation can be done  from the adaptor itself depending on some condition.

Do you agree that multiple simultaneous backends is a good goal? That one is much simpler than the multiple adaptors I think

**Comment by alisterburt** [comment]
closing as things have now changed and multiple backends are more possible, if not yet entirely supported

**Pull request closed without merging**
